---

base_config: # applied to all DAGs unless overwritten
  dwh_engine: postgres
  dwh_conn_id: dwh
  airflow_conn_id: airflow
  start_date: 2020-10-01 00:00:00+00:00
  schedule_interval: !!python/object/apply:datetime.timedelta
    - 1 # days
    - 0 # seconds
  schedule_interval_backfill: !!python/object/apply:datetime.timedelta
    - 7
  schedule_interval_future: !!python/object/apply:datetime.timedelta
    - 0
    - 28800
  # For fullcremental loads
  schedule_interval_full_refresh: !!python/object/apply:datetime.timedelta
    - 1 # days
    - 0 # seconds
  schedule_interval_incremental: !!python/object/apply:datetime.timedelta
    - 0 # days
    - 28800 # seconds
  read_right_users:
    - i_dont_exist
  additional_task_args:
    retries: 1
    retry_delay: !!python/object/apply:datetime.timedelta
      - 0
      - 30
    email_on_retry: False
    email_on_failure: False
    # email: ['me+ewahairflowerror@mail.com']
el_dags:
  EL_Aircall:
    dag_strategy: incremental
    el_operator: aircall
    target_schema_name: raw_aircall
    start_date: 2020-10-31 00:00:00+00:00
    operator_config:
      general_config:
        source_conn_id: aircall
        reload_data_from: 2020-10-31 00:00:00+00:00
        wait_for_seconds: 120
      tables:
        calls: {}

  EL_Aircall_FR:
    dag_strategy: fr
    el_operator: aircall
    target_schema_name: raw_aircall_fr
    operator_config:
      general_config:
        source_conn_id: aircall
      tables:
        users: {}
        numbers: {}
        contacts: {}
        tags_table:
          resource: tags
        teams: {}

  EL_Airflow:
    dag_strategy: atomic
    el_operator: airflow
    target_schema_name: raw_airflow_metadata
    operator_config:
      tables:
        {% for conn_name in ["airflow_api", "airflow_via_ssh_vpn", "airflow_via_ssh", "airflow_via_url", "airflow_multi_hops"] %}
          {{ conn_name }}_dags:
            endpoint: dags
            source_conn_id: "{{ conn_name }}"
          {{ conn_name }}_task_instance:
            endpoint: taskInstance
            source_conn_id: "{{ conn_name }}"
          {{ conn_name }}_dag_runs:
            endpoint: dagRuns
            source_conn_id: "{{ conn_name }}"
          {{ conn_name }}_connections:
            endpoint: connections
            source_conn_id: "{{ conn_name }}"
          {{ conn_name }}_variables:
            endpoint: variables
            source_conn_id: "{{ conn_name }}"
          {{ conn_name }}_health:
            endpoint: health
            source_conn_id: "{{ conn_name }}"
        {% endfor %}


  EL_BigQuery:
    dag_strategy: fr
    el_operator: bq
    target_schema_name: raw_bq_fr
    operator_config:
      general_config:
        source_conn_id: bq
        source_schema_name: ds1
        source_database_name: gemma-287313
      tables:
        weights:
          source_table_name: bijan_weight

  EL_BigQuery_events: !yml_from_file secret_dag_bq.yml
  EL_BigQuery_SQL: !yml_from_file secret_dag_bq_sql.yml
  # EL_BigQuery_events_sharded: !yml_from_file secret_dag_bq_sharded.yml

  EL_DynamoDB:
    dag_strategy: full-refresh
    el_operator: dynamodb
    target_schema_name: raw_dynamodb
    operator_config:
      general_config:
        source_conn_id: dynamodb_conn
        region_name: eu-central-1
      tables:
        admins:
          partition_key: email
        all_users:
          partition_key: email
          source_table_name: users
        invoices:
          partition_key: invoice_id
          sort_key: status
          source_table_name: invoice-reference

  EL_Facebook: !yml_from_file secret_dag_facebook.yml

  EL_FX:
    dag_strategy: full refresh
    el_operator: fx
    target_schema_name: raw_fx
    operator_config:
      general_config:
        frequency: daily
        load_data_from: 2016-12-01 00:00:00+00:00 # tbd airflow 2.0 issue
      tables:
        {% for currency in ["EUR", "CAD", "GBP", "CHF", "ARS", "CLP", "RON", "MYR", "AUD"] %}
          daily_fx_rates_usd_{{ currency|lower() }}:
            currency_pair:
              - USD
              - {{ currency|upper() }}
        {% endfor %}

  EL_GAds: !yml_from_file secret_dag_gads.yml

  EL_GA: !yml_from_file secret_dag_google_analytics.yml

  # EL_GMaps: tbd

  EL_GSheets: !yml_from_file secret_dag_gsheets.yml

  EL_Hubspot:
    dag_strategy: fr
    el_operator: hubspot
    target_schema_name: raw_hubspot
    operator_config:
      general_config:
        source_conn_id: hubspot
      tables:
        companies:
          associations:
            - deals
            - contacts
        contacts:
          properties:
            - new_ip_address
            - new_referer
            - new_user_agent
            - new_utm_campaign
            - new_utm_content
        deals:
          associations: line_items
          properties:
            - amount
            - dealstage
            - dealtype
            - ignoreme
          exclude_properties:
            - ignoreme
        feedback_submissions: {}
        line_items: {}
        products: {}
        tickets: {}
        quotes_table:
          object: quotes
        properties: {}
        owners: {}

  EL_Mailchimp:
    dag_strategy: fr
    el_operator: mailchimp
    target_schema_name: raw_mailchimp
    dwh_conn_id: ssh_dwh
    operator_config:
      general_config:
        source_conn_id: mailchimp
      tables:
        reports:
          resource: reports
        lists:
          resource: lists
        lists_hashed:
          resource: lists
          hash_columns: name
        conversations:
          resource: conversations
        campaigns: {}
        campaigns_hashed:
          resource: campaigns
          hash_columns:
            - web_id
            - type
            - status
            - sed_time

  EL_Mailingwork:
    dag_strategy: fr
    el_operator: mailingwork
    target_schema_name: raw_mailingwork
    dwh_conn_id: snowflake_conn
    dwh_engine: snowflake
    operator_config:
      general_config:
        source_conn_id: mailingwork
      tables:
        fields:
          endpoint: getfields
        lists:
          endpoint: getlists
        mailings:
          endpoint: getmailings
        media:
          endpoint: getmedia
        export_recipients:
          endpoint: exportrecipients
          primary_key_column_name: id
          page_size: 2000
          normal_params:
            "advanced[compact]": 1
          iter_param:
            name: listId
            values:
              - 227
              - 3
              - 2

  EL_MongoDB: !yml_from_file secret_dag_mongodb.yml
  EL_MongoDB_2: !yml_from_file secret_dag_mongodb_2.yml
  EL_MongoDB_3: !yml_from_file secret_dag_mongodb_3.yml
  EL_MongoDB_4: !yml_from_file secret_dag_mongodb_4.yml
  EL_MongoDB_5: !yml_from_file secret_dag_mongodb_5.yml

  EL_MySQL_Atomic: !yml_from_file secret_dag_mysql_atomic.yml
  EL_MySQL_Symfony: !yml_from_file secret_dag_mysql.yml

  EL_Oracle: !yml_from_file secret_dag_oracle_to_snowflake.yml
  EL_Oracle_2: !yml_from_file secret_dag_oracle_fullcremental.yml
  EL_Oracle_FR: !yml_from_file secret_dag_oracle_fr.yml
  EL_Oracle_FR_compress: !yml_from_file secret_dag_oracle_fr_compress.yml

  EL_Pipedrive:
    dag_strategy: fr
    el_operator: pipedrive
    target_schema_name: raw_pd
    operator_config:
      general_config:
        source_conn_id: pipedrive
      tables:
        deals: {}
        activity_fields:
          pipedrive_object: activityFields
        currencies: {}
        leads: {}
        activities: {}
        notes: {}

  EL_Postgres:
    dag_strategy: fr
    el_operator: postgres
    target_schema_name: raw_pg_fr
    operator_config:
      general_config:
        source_conn_id: dwh # load from dwh to dwh
        source_schema_name: public
      tables:
        dag:
          batch_size: 10

  EL_Postgres_2:
    dag_strategy: full-refresh
    el_operator: postgres
    target_schema_name: raw_mf
    operator_config:
      general_config:
        source_conn_id: mf
        source_schema_name: public
      tables:
        product_prices:
          sql_select_statement: !text_from_file secret_sql_query.sql

  EL_S3: !yml_from_file secret_dag_s3.yml
  EL_S3_2: !yml_from_file secret_dag_s3_2.yml
  EL_S3_3: !yml_from_file secret_dag_s3_3.yml

  EL_Salesforce:
    dag_strategy: incremental
    el_operator: sf
    target_schema_name: raw_sf
    operator_config:
      general_config:
        reload_data_from: 2010-01-01 00:00:00+00:00
        source_conn_id: salesforce
      tables:
        User: {}
        Lead: {}
        LeadHistory: {}

  # EL_Shopify: tbd

  EL_Stripe:
    dag_strategy: fr
    el_operator: stripe
    target_schema_name: raw_stripe
    operator_config:
      general_config:
        source_conn_id: stripe
      tables:
        Account: {}
        Balance: {} # resource defaults to table name
        balance_transactions:
          resource: BalanceTransaction
        Customer:
          rename_columns:
            currency: currency_name
            delinquent: is_delinquent
        Payout: {}
        Charge:
          expand: # expand a list of strings as required
            - 'data.customer'
        products:
          resource: Product
        refunds:
          resource: Refund
        transactions:
          resource: issuing.Transaction

  # EL_Zendesk: tbd

  Update_GSheet:
    dwh_engine: gsheets
    dwh_conn_id: google_service_account_key
    dag_strategy: fr
    el_operator: postgres
    target_schema_name: 1peh2ztnhqDJ98Qmp8PK0FMmJxJMzTaLKWUq37cDfujA
    schedule_interval: !!python/object/apply:datetime.timedelta
      - 0
      - 60 # every minute
    operator_config:
      general_config:
        add_metadata: False
        source_conn_id: dwh
        source_schema_name: public
      tables:
        Upload Test:
          sql_select_statement: "select 1 as a, 2 as b, 'c' as c union all select 3, 4, 'd'"

...
